import 'package:flutter/material.dart';

void main() {
  runApp(
    const MaterialApp(debugShowCheckedModeBanner: false, home: CustomList()),
  );
}

class CustomList extends StatefulWidget {
  const CustomList({super.key});

  @override
  State<CustomList> createState() => _CustomListState();
}

class _CustomListState extends State<CustomList> {
  final List<String> items = [
    "Apple",
    "Banana",
    "Mango",
    "Orange",
    "Grapes",
    "Papaya",
    "Pineapple",
    "Guava",
    "Watermelon",
    "Muskmelon",
    "Strawberry",
    "Blueberry",
    "Raspberry",
    "Blackberry",
    "Cherry",
    "Peach",
    "Plum",
    "Apricot",
    "Kiwi",
    "Pomegranate",
    "Pear",
    "Fig",
    "Date",
    "Coconut",
    "Litchi",
    "Jackfruit",
    "Custard Apple (Sitaphal)",
    "Dragon Fruit",
    "Avocado",
    "Passion Fruit",
    "Star Fruit",
    "Mulberry",
    "Cranberry",
    "Gooseberry (Amla)",
    "Olive",
    "Tangerine",
    "Clementine",
    "Mandarin",
    "Pomelo",
    "Lemon",
    "Lime",
    "Grapefruit",
    "Nectarine",
    "Persimmon",
    "Quince",
    "Durian",
    "Rambutan",
    "Longan",
    "Mangosteen",
    "Sapodilla (Chikoo)",
    "Breadfruit",
    "Soursop",
    "Sugar Apple",
    "Tamarind",
    "Bael",
    "Jamun",
    "Karonda",
    "Wood Apple",
    "Rose Apple",
    "Indian Fig",
    "Loquat",
    "Apple",
    "Banana",
    "Mango",
    "Orange",
    "Grapes",
    "Papaya",
    "Pineapple",
    "Guava",
    "Watermelon",
    "Muskmelon",
    "Strawberry",
    "Blueberry",
    "Raspberry",
    "Blackberry",
    "Cherry",
    "Peach",
    "Plum",
    "Apricot",
    "Kiwi",
    "Pomegranate",
    "Pear",
    "Fig",
    "Date",
    "Coconut",
    "Litchi",
    "Jackfruit",
    "Custard Apple (Sitaphal)",
    "Dragon Fruit",
    "Avocado",
    "Passion Fruit",
    "Star Fruit",
    "Mulberry",
    "Cranberry",
    "Gooseberry (Amla)",
    "Olive",
    "Tangerine",
    "Clementine",
    "Mandarin",
    "Pomelo",
    "Lemon",
    "Lime",
    "Grapefruit",
    "Nectarine",
    "Persimmon",
    "Quince",
    "Durian",
    "Rambutan",
    "Longan",
    "Mangosteen",
    "Sapodilla (Chikoo)",
    "Breadfruit",
    "Soursop",
    "Sugar Apple",
    "Tamarind",
    "Bael",
    "Jamun",
    "Karonda",
    "Wood Apple",
    "Rose Apple",
    "Indian Fig",
    "Loquat",
    "Apple",
    "Banana",
    "Mango",
    "Orange",
    "Grapes",
    "Papaya",
    "Pineapple",
    "Guava",
    "Watermelon",
    "Muskmelon",
    "Strawberry",
    "Blueberry",
    "Raspberry",
    "Blackberry",
    "Cherry",
    "Peach",
    "Plum",
    "Apricot",
    "Kiwi",
    "Pomegranate",
    "Pear",
    "Fig",
    "Date",
    "Coconut",
    "Litchi",
    "Jackfruit",
    "Custard Apple (Sitaphal)",
    "Dragon Fruit",
    "Avocado",
    "Passion Fruit",
    "Star Fruit",
    "Mulberry",
    "Cranberry",
    "Gooseberry (Amla)",
    "Olive",
    "Tangerine",
    "Clementine",
    "Mandarin",
    "Pomelo",
    "Lemon",
    "Lime",
    "Grapefruit",
    "Nectarine",
    "Persimmon",
    "Quince",
    "Durian",
    "Rambutan",
    "Longan",
    "Mangosteen",
    "Sapodilla (Chikoo)",
    "Breadfruit",
    "Soursop",
    "Sugar Apple",
    "Tamarind",
    "Bael",
    "Jamun",
    "Karonda",
    "Wood Apple",
    "Rose Apple",
    "Indian Fig",
    "Loquat",
  ];
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("ListView Builder")),
      body: ListView.builder(
        itemCount: items.length,
        itemBuilder: (context, index) {
          return ListTile(
            leading: const Icon(Icons.verified_user),
            title: Text("Item ${items[index]}"),
            trailing: IconButton(
              icon: const Icon(Icons.delete),
              onPressed: () {
                setState(() {
                  items.removeAt(index);
                });
              },
            ),
          );
        },
      ),
    );
  }
}
